### ISSUE TITLE
Compatibility between ISO BMFF and CMAF byte stream format

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/CMAF-Byte-Stream#14]
Please add additional aspects that are not compatible.

**Comment by poolec** [comment]
Propose adding a bullet point here noting the inband parameters issue:

* For many CMAF video profiles, support for inband parameter sets is required whereas in the ISO BMFF byte stream format specification support is merely recommended.

**Comment by haudiobe** [comment]
AHG Call 2020/10/19:
addressed in revised draft. Unless any comments are received, the issue will be closed by the next meeting.

**Comment by haudiobe** [comment]
Implemented: https://1drv.ms/w/s!AiNJEPgowJnWgqsz3EFQvnMD7BhN0w?e=42BwJJ
