### ISSUE TITLE
A.5: "metadata" kind - how to use?

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/CMAF-Byte-Stream#16]
Editor's Note:  Should "metadata" kind remain possible in a CMAF conforming presentation? Answer here will inform lower usage of metadata fallback as well.

**Comment by technogeek00** [comment]
My last call notes has it noted that metadata kind is not possible with CMAF currently and that the clause should be collapsed to an empty string. If there has not been further discussion I would move to implement the description reduction.

**Comment by haudiobe** [comment]
AHG Call 2020/10/19:
addressed in revised draft. Unless any comments are received, the issue will be closed by the next meeting.

**Comment by haudiobe** [comment]
Implemented: https://1drv.ms/w/s!AiNJEPgowJnWgqsz3EFQvnMD7BhN0w?e=42BwJJ
