### ISSUE TITLE
A.5: Language in CTA-608/708

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/CMAF-Byte-Stream#17]
Editor's Note:  Carry over from ISOBMFF definition, service language may not match encapsulating track, do we have a better identifier?

**Comment by technogeek00** [comment]
After a bit more research I've not found a suitable replacement, CMAF would need to define an in-box identifier in addition to the compatibility brand. Alternatively it could be supplied by the application player atop the media engine

**Comment by technogeek00** [comment]
Interesting suggestion in #21 but may require changes in CMAF

**Comment by haudiobe** [comment]
AHG Call 2020/10/19:
no updates, but will monitor proposal in #21. Unless any comments are received, the issue will be closed by the next meeting.

**Comment by haudiobe** [comment]
Call 2020/11/19 - closed.
