### ISSUE TITLE
typo - former vs latter?

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/CMAF-Byte-Stream#20]
Re
> The CMAF track format is derived from [ISOBMFF] and therefore shares MIME types with the former format. 

I think former here should be latter?

**Comment by haudiobe** [comment]
Thanks - fixed in the revised version before publication: https://1drv.ms/w/s!AiNJEPgowJnWgqINU8ZkF1ZVNP6Tag?e=FbPwdE
