### ISSUE TITLE
Use of a compatibility brand in a file type box or track type box

### ISSUE THREAD

**Issue by krasimirkolarov** [cta-wave/CMAF-Byte-Stream#21]
The use of a compatibility brand in a file type box or track type box to indicate the presence of certain types of media data should neither be the only available means of discovery nor the primary means; this is rightfully the job of the sample description. In particular, we recommend the definition and use of a child box in the video sample description in order to signal the presence and type of closed captions embedded in video. Such a box can be far more informative than a compatibility brand, in that it can include a declaration of the captioning language as well as the type (608 vs 708).

**Comment by technogeek00** [comment]
@krasimirkolarov am I right to assume you are primarily speaking to the 608/708 signalling? 

I agree what you describe would provide a far better descriptive definition for the caption tracks, but this level of signalling is not specified by CMAF and the mapping constraints were written based on the data stipulated by the specification, the compatibility brand being the only addition. Could we take your suggestion back to MPEG to have it further clarify this signalling?

**Comment by krasimirkolarov** [comment]
Yes.

We should certainly look at what CMAF can and perhaps should recommend in addition to the compatible brand

**Comment by haudiobe** [comment]
AHG 2020/10/19:
* we cannot do anything in the Byte Stream format on this
* However, we agree that the proposal is useful and we would likely adopt this if available.
* We inform MPEG on this and ask them if they may want to update the CMAF specification.

**Comment by haudiobe** [comment]
Implemented: https://1drv.ms/w/s!AiNJEPgowJnWgqsz3EFQvnMD7BhN0w?e=42BwJJ

**Comment by krasimirkolarov** [comment]
Addressed in TuC in MPEG CMAF spec
