### ISSUE TITLE
Preference to use textual user data item

### ISSUE THREAD

**Issue by krasimirkolarov** [cta-wave/CMAF-Byte-Stream#22]
We prefer the use of a textual userdata item to the use of the name field of the HandlerBox for human-readable labeling of tracks. HandlerBox names have not been historically used for human-readable labels, and therefore long-established practice conflicts with the suggested usage here.

**Comment by technogeek00** [comment]
@krasimirkolarov Is there a box already standardized for this in CMAF? The text currently for the `label` attribute is just utilizing the original text from the base ISOBMFF profile. I could not find a better CMAF defined reference so I kept it as is, though I do understand the label is typically something like `SoundHandler`, not great.

An alternative that could be pursued is generation of the label from the other box data, but that might be over-complicating it a bit.

**Comment by krasimirkolarov** [comment]
_"@krasimirkolarov Is there a box already standardized for this in CMAF? The text currently for the label attribute is just utilizing the original text from the base ISOBMFF profile. I could not find a better CMAF defined reference so I kept it as is, though I do understand the label is typically something like SoundHandler, not great."_

The concern is that it will not meet the need for a human-readable label as it is produced by currently available tools, so rather than "not great" we'd rather say "too often unsuitable".

Defining a userdata type for the purpose or adopting an existing userdata type from another ISO BMFF-based specification, for use in track userdata to carry a human-readable label, may be feasible. 3GPP 'titl' may be a candidate.

_"An alternative that could be pursued is generation of the label from the other box data, but that might be over-complicating it a bit."_

Our implementation does something like that as a fallback, when no appropriate human-readable titling or labeling can be found. A label assembled from the media type, track language, and track ID (or some other uniqueifier, such as a track number) is not overly complicated.

**Comment by haudiobe** [comment]
AHG 2020/10/19:
* we can improve this here to have a constructive label. @technogeek00 will provide a proposal
* we also believe that the MPEG CMAF specification can be improved taking the comment above into account.

**Comment by technogeek00** [comment]
Basic proposal for text and audio, open to suggestions on video, its far less clear cut.

**Comment by haudiobe** [comment]
Implemented: https://1drv.ms/w/s!AiNJEPgowJnWgqsz3EFQvnMD7BhN0w?e=42BwJJ
