### ISSUE TITLE
Non-zero durations in an edit?

### ISSUE THREAD

**Issue by krasimirkolarov** [cta-wave/CMAF-Byte-Stream#23]
Is it not the case that for single-track fMP4 a non-zero edit duration must be equal to the fragment_duration if present in the 'mvex' box? If so, why is there a need to support non-zero durations in an edit?

**Comment by haudiobe** [comment]
AHG 2020/10/19:
* Good point, second one seems not needed. Where is the source? CMAF spec or ISO BMFF Byte Stream format. It comes from Byte Stream format.
* In CMAF the non-zero is not permitted and hence we should correct this here.

**Comment by haudiobe** [comment]
Implemented: https://1drv.ms/w/s!AiNJEPgowJnWgqsz3EFQvnMD7BhN0w?e=42BwJJ

**Comment by krasimirkolarov** [comment]
Addressed in TuC in MPEG CMAF spec
