### ISSUE TITLE
On Inband Sources

### ISSUE THREAD

**Issue by krasimirkolarov** [cta-wave/CMAF-Byte-Stream#24]
In the section regarding MPEG-CMAF Inband Sources, it would be helpful to indicate that the user agent may receive some or all of the necessary information from a manifest file, if a manifest is available in a format known to the user agent. The process of gleaning HTML track attributes from inband sources can be employed when no such manifest is available or when it is not sufficiently complete for the purpose.

**Comment by technogeek00** [comment]
It's worth adding this as a note to the introduction in A.1. The Annex A is meant to be added as an additional section to [the general in-band sourcing guidelines](https://dev.w3.org/html5/html-sourcing-inband-tracks/) (the unofficial status being a common point of confusion).

The expectation would be that a Type 1 player implementation in a browser could rely on both manifest and in-band provided data as it is directly handling both information sources. A Type 3 player implementation would only ever see the in-band provided data, but there are a few places where the application hosted player could provide better contextual information to the media engine if the APIs allowed it, unsure if they do, but example of this would be #15

**Comment by haudiobe** [comment]
AHG Call 2020/10/19:
* Propose to add the discussion. It is informative rather then it will change anything
*

**Comment by technogeek00** [comment]
Added a note in A.1 Introduction stating this sourcing description is for CMAF presentations provided to user agents via MSE/EME and that a manifest sourcing description would take precedence.

**Comment by haudiobe** [comment]
Implemented: https://1drv.ms/w/s!AiNJEPgowJnWgqsz3EFQvnMD7BhN0w?e=42BwJJ
