### ISSUE TITLE
Section 4 typo

### ISSUE THREAD

**Issue by sdp198** [cta-wave/CMAF-Byte-Stream#26]
In the paragraph under Table 1 it says:
"In addition to an optional Segment Type Box (styp), a single Movie Fragment Box (moof), followed by a Media Data Boxes (mdat),..."

It shouldn't say Media Data Boxes, but Media Data Box as there is only one (confirmed by Table 1).

**Comment by haudiobe** [comment]
AHG 2020/11/19: Thank you

**Comment by haudiobe** [comment]
Implemented: https://1drv.ms/w/s!AiNJEPgowJnWgqsz3EFQvnMD7BhN0w?e=42BwJJ
