### ISSUE TITLE
Inband tracks: track order

### ISSUE THREAD

**Issue by poolec** [cta-wave/CMAF-Byte-Stream#30]
The inband tracks part of the CMAF byte stream doc includes section A.3 on Track Order:
> A track may be created for each CMAF switching set signaled by the manifest. The order of track depends on the application.

As written this would seem to apply only where the browser directly supports DASH or HLS (a so-called "type 1" player), rather than when using MSE since it's only in that case that the browser sees any manifest.  With MSE, there aren't generally multiple tracks known to the user-agent.  It is only likely to see a single CMAF Switching Set at a time, which can only contribute a single Track.

I don't think this specification needs to cover "type 1" players - there is already a DASH section in the inband tracks spec which tells you how to populate track metadata from a DASH MPD.  Having a CMAF mapping that applies in that case too would lead to conflict and confusion.

I'd propose replacing the text here with the following:
> In the case where the user-agent is passed a manifest referencing CMAF content, rather than CMAF content directly, multiple tracks may be created, one for each CMAF switching set signaled by the manifest.  The order of tracks is not defined here.
> 
> NOTE: Track ordering does not apply when MSE is used and a single CMAF switching set of a particular media type is chosen by the application.

Or perhaps the entire CMAF inband tracks mapping should be restricted more explicitly to the MSE case?

**Comment by technogeek00** [comment]
@poolec You are right the mixture of type 1 and type 3 description makes this description muddy. I like the idea of stating the restriction of the description to type 3 players and simplifying the A.3 to your descriptive note:

> Track ordering does not apply when MSE is used and a single CMAF switching set of a particular media type is chosen by the application.

**Comment by technogeek00** [comment]
Description around Type 3 players will also solve #24

**Comment by technogeek00** [comment]
Updated A.3 to note that track ordering does not apply.

**Comment by haudiobe** [comment]
Call 2020/11/19: Agreed. We update A.3 as follows

Track ordering does not apply to this sourcing profile as CMAF is provided to the user agent via MSE and only a single CMAF switching set of a particular media type is chosen by the application.

**Comment by haudiobe** [comment]
Implemented: https://1drv.ms/w/s!AiNJEPgowJnWgqsz3EFQvnMD7BhN0w?e=42BwJJ
